# DS 3000/CS 3200 Lab 1

Due: Tuesday May 12 in-class

### Submission Instructions
Upload this `ipynb` file to GitHub as per the instructions in Part 4, and then to Gradescope.  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the `ipynb` file to GitHub and verify that the correct version is represented on Gradescope.

#### Note:
Future Labs/Homeworks do not need to be submitted via GitHub; I'm only asking you to do it on this Lab to practice with using GitHub (as it will be important to be familiar with its usage for the project). For some of you this is likely already second nature.

### Tips for success
- Collaborate: bounce ideas off of each other, if you are having trouble you can ask your classmates or Dr. Gerber for help with specific issues, however...
- [(See)](http://www.northeastern.edu/osccr/academic-integrity), i.e. you are welcome to **talk about/discuss** (*not* show or allow each other to copy your answers to) the problems.

# Part 1 (40 points): Intro to Markdown

You will use the markdown language in formatting parts of your project. Use it below to create your own brief wikipedia-esque description of a topic related to International Government and Politics. 

Your mini-wiki page must include:
- three headers: a title, subtitle and subsubtitle (the #, ##, ### syntax)
- an embedded image from a web address (use an [image hosting site](https://makeawebsitehub.com/free-photo-hosting/) if you'd like to upload your own)
- a **markdown** table of size at least 9 cells (i.e. 3 by 3, or 5 by 2)
- a list in **markdown**
- a working hyperlink to another website

To practice typing in math mode, also include a LaTeX formula describing how your final grade is going to be calculated based on the syllabus, something like:

$$grade = weight_1*score_1 + weight_2*score_2$$

Please be **brief** in your text.

# United Nations

The United Nations has become the foremost forum to address issues that transcend national boundaries.


![United Nations Headquarters](https://gps.bard.edu/hubfs/AdobeStock_669843932_Editorial_Use_Only.jpeg)


## Overview

The UN has reprentatives from 193 member states. It is the world's largest intergovernmental organization. All members have equal representation in the General Assembly.


### Division

The UN is divided into several major bodies:

- General Assembly
- Security Council
- International Court of Justice
- Secretariat
- Economic and Social Council

| Organization Body | Main Purpose | Location |
|---|---|---|
| General Assembly | Debate global issues | New York |
| Security Council | Maintain peace | New York |
| International Court of Justice | Solve disputes | The Hague |

Read more at the [official United Nations website](https://www.un.org).

The formula for calculating a final grade can be written as:

$$
grade = 0.6 \times homeworks and labs + 0.4 \times inclass activities
$$

Markdown and LaTeX example: $\alpha^2$


# Part 2: Numpy
## Part 2.1: Creating Arrays (10 points)

Create the following two arrays using the NumPy library and then print them out. Call the first array `array_a` and the second array `array_b` (make sure you keep the `import` statement below):

$$\mathbf{array_a} = \begin{bmatrix}3 & 8 & -2 & 3\\
.5 & -1 & 6 & 4\\
-5 & 7 & -42 & 2
\end{bmatrix}$$

$$\mathbf{array_b} = \begin{bmatrix}42 & 38 & 34\\
30 & 26 & 22\\
18 & 14 & 10\\
6 & 2 & -2\\
-6 & -10 & -14
\end{bmatrix}$$

In [1]:
# make sure to import numpy library
import numpy as np
array_a = np.array([[3,8,-2,3],
                    [0.5,-1,6,4],
                    [-5,7,-42,2]])
array_b = np.array([[42,38,34],
                    [30,26,22],
                    [18,14,10],
                    [6,2,-2],
                    [-6,-10,-14]])

In [2]:
# uncomment below to print array_a
array_a

array([[  3. ,   8. ,  -2. ,   3. ],
       [  0.5,  -1. ,   6. ,   4. ],
       [ -5. ,   7. , -42. ,   2. ]])

In [3]:
# uncomment below to print array_b
array_b

array([[ 42,  38,  34],
       [ 30,  26,  22],
       [ 18,  14,  10],
       [  6,   2,  -2],
       [ -6, -10, -14]])

## Part 2.2: Exploring Arrays (15 points)

1. Give the shape, size, ndim, and nbytes for each of the two arrays.
1. Take the transpose of both arrays. Call these `t_array_a` and `t_array_b`.
1. Try to add `array_a` and `t_array_b` (*prove* and *show* you did this with commented out code), then remove the last column of `t_array_b` and try to add them again. In a markdown cell, explain what happened.

In [4]:
#1
print(array_a.shape)
print(array_a.size)
print(array_a.ndim)
print(array_a.nbytes)
print(array_b.shape)
print(array_b.size)
print(array_b.ndim)
print(array_b.nbytes)

#2
t_array_a = np.transpose(array_a)
t_array_b = np.transpose(array_b)

print("Array A:")
print(t_array_a)
print("Array B: ")
print(t_array_b)

#3
#print(array_a+t_array_b)

t_array_b_removed = t_array_b[:, :-1]

print("array_a + t_array_b_removed: ")
print(array_a + t_array_b_removed)

(3, 4)
12
2
96
(5, 3)
15
2
60
Array A:
[[  3.    0.5  -5. ]
 [  8.   -1.    7. ]
 [ -2.    6.  -42. ]
 [  3.    4.    2. ]]
Array B: 
[[ 42  30  18   6  -6]
 [ 38  26  14   2 -10]
 [ 34  22  10  -2 -14]]
array_a + t_array_b_removed: 
[[ 45.   38.   16.    9. ]
 [ 38.5  25.   20.    6. ]
 [ 29.   29.  -32.    0. ]]


array_a and t_array_b cannot be added because they are not the same size arrays. array_a and t_array_b_removed are able to be added because they are the same size.

# Part 3: Pandas
## Part 3.1: Reading in Data (5 points)

On Canvas is the `train_stations_europe.csv` file. It was adapted from [this Kaggle data set](https://www.kaggle.com/datasets/headsortails/train-stations-in-europe). Read this data set in, using the `id` as the index column, and print the first few rows of the data. Make sure you keep the `import` statement below!

In [4]:
# make sure to import pandas library
import pandas as pd
df = pd.read_csv("train_stations_europe.csv", index_col = "id")
print(df.head())

                       name   latitude  longitude  parent_station_id country  \
id                                                                             
1   Chateau-Arnoux-St-Auban  44.081790   6.001625                NaN      FR   
2   Chateau-Arnoux-St-Auban  44.061565   5.997373                1.0      FR   
3     Chateau-Arnoux Mairie  44.063863   6.011248                1.0      FR   
4           Digne-les-Bains  44.350000   6.350000                NaN      FR   
6           Digne-les-Bains  44.088710   6.222982                4.0      FR   

       time_zone  is_city  is_main_station  is_airport  
id                                                      
1   Europe/Paris     True            False       False  
2   Europe/Paris    False             True       False  
3   Europe/Paris    False            False       False  
4   Europe/Paris     True            False       False  
6   Europe/Paris    False             True       False  


## Part 3.2: Manipulating Data (20 points)

1. Create a subset of the data set which (a) **includes** only train stations in Belgium and (b) **excludes** all train stations which are **not** in a city. Make sure to save this subset as a new data frame and print the first few rows of the data.
1. Use the `.describe()` function to produce summary statistics for the subset from the previous part. Create a markdown cell and explain:
    - What Series did the `.describe()` function run on? What Series did it not run on? What is the difference, and what does this mean the `.describe()` function is used for?

In [5]:
belgiumcities = df[(df["country"] == "BE") & (df["is_city"] == False)]
print(belgiumcities.head())
print(belgiumcities.describe())

                   name   latitude  longitude  parent_station_id country  \
id                                                                         
1121  Tournai Frontiere        NaN        NaN                NaN      BE   
1122          Froyennes        NaN        NaN                NaN      BE   
1313           Mouscron        NaN        NaN                NaN      BE   
1354    Quevy Frontiere        NaN        NaN             6003.0      BE   
5893     Bruxelles-Midi  50.835374   4.335695             5974.0      BE   

            time_zone  is_city  is_main_station  is_airport  
id                                                           
1121  Europe/Brussels    False            False       False  
1122  Europe/Brussels    False            False       False  
1313  Europe/Brussels    False            False       False  
1354  Europe/Brussels    False            False       False  
5893  Europe/Brussels    False             True       False  
         latitude   longitude  pa

In [6]:
#The 'describe()' function ran on the numerical Series in the data frame rather than text-based series. Numerical Series allows for calculations. This shows that this function is mainly used to summarize numerical data.

# Part 4: GitHub (10 points)

The below process is obviously not necessary, but designed to give students with minimal Git experience some practice using Git in the command line. When you finish the first three parts of this lab, give one last restart and run all to this file. Then, go to the [DS 3000 GitHub](https://github.com/eaegerber/ds3000_summer26), fork it and then clone it to your local machine. Then:

- In the forked and cloned ds3000_summer26 repo, make a new branch (`git checkout -b lab-upload`)
- Create a folder with your name (as Dr. Gerber did)
- Navigate to that folder and place this jupyter notebook inside
- Add the file as the change to be committed (`git add .\Lab1_MyName.ipynb`)
- Check `git status`, your changes should be staged
- Commit the changes with a short message (`git commit -m "My message"`)
- Push the repository to GitHub (`git push origin lab-upload`)
- Navigate the the GitHub in the browser and create a pull request
- Once the pull request is merged, you can delete your branch in the "Pull Requests" tab in the browser
- Finally, upload the Lab to Gradescope. When you do so, it will give you the option to do it via GitHub; do that.
  - **Note**: you only have to do this for this assignment; future assignments can be uploaded directly to Gradescope